AWSTemplateFormatVersion: '2010-09-09'

Description: This AWS CloudFormation Template that configures the Container DevSecOps workshop. 

Parameters:

  BucketName:
    Type: String
    Default: sa-security-specialist-workshops-us-east-2
    Description: Source bucket for workshop CloudFormation yaml's

Resources:

  AnchoreVpcStack:
    Type: AWS::CloudFormation::Stack
    Properties:
      Parameters:
        EnvironmentName: container-devsecops-wksp
      TemplateURL: !Join [ '/', [ 'https://s3.amazonaws.com', !Ref BucketName, 'devsecops/containers/anchore-vpc.yml'  ] ]

  AnchoreStack:
    DependsOn: AnchoreVpcStack
    Type: AWS::CloudFormation::Stack
    Properties:
      Parameters:
        ResourceName: container-devsecops-wksp
        BucketName: !Ref BucketName
      TemplateURL: https://aws101-dams.s3-ap-southeast-1.amazonaws.com/anchore-fargate.yml

  InitialPipeline:
    DependsOn: AnchoreStack
    Type: AWS::CloudFormation::Stack
    Properties:
      Parameters:
        ResourceName: container-devsecops-wksp
        FailWhen: High
        BucketName: !Ref BucketName
      TemplateURL: !Join [ '/', [ 'https://s3.amazonaws.com', !Ref BucketName, 'devsecops/containers/pipeline-setup.yml'  ] ]
  

Outputs: {}